CREATE TABLE customer (
cid int IDENTITY(1, 1) PRIMARY KEY,
cname varchar(20) NOT NULL,
age int NOT NULL,
gender char(1) NOT NULL,
email varchar(40) NOT NULL UNIQUE,
pass varchar(15) NOT NULL
); 

CREATE TABLE runway (
runId int IDENTITY(1, 1) PRIMARY KEY,
runStatus bit NOT NULL,
length int NOT NULL
);

CREATE TABLE airline (
alCode varchar(3) PRIMARY KEY,
alName varchar(20) NOT NULL
);

CREATE TABLE airport (
aCode char(3) PRIMARY KEY,
aName varchar(70) NOT NULL,
loc varchar(50) NOT NULL
);

CREATE TABLE flight (
fNum char(6) PRIMARY KEY,
model varchar(20) NOT NULL,
capacity int NOT NULL,
alCode varchar(3) FOREIGN KEY REFERENCES airline(alCode) ON DELETE CASCADE,
);

CREATE TABLE route (
rid int IDENTITY(1, 1) PRIMARY KEY,
rtype bit NOT NULL,
dtime datetime NOT NULL,
fNum char(6) FOREIGN KEY REFERENCES flight(fNum) ON DELETE CASCADE,
runId int FOREIGN KEY REFERENCES runway(runId) ON DELETE CASCADE,
locId char(3) FOREIGN KEY REFERENCES airport(aCode) ON DELETE CASCADE
);

CREATE TABLE ticket(
tNo int IDENTITY(1, 1) PRIMARY KEY,
cid int FOREIGN KEY REFERENCES customer(cid) ON DELETE CASCADE,
rid int FOREIGN KEY REFERENCES route(rid) ON DELETE CASCADE,
seatNum char(3) NOT NULL,
class char(1) NOT NULL,
mealOption bit NOT NULL
);

INSERT INTO airline VALUES ('EI', 'Aer Lingus')
INSERT INTO airline VALUES ('G9', 'Air Arabia')
INSERT INTO airline VALUES ('AK', 'Air Asia')
INSERT INTO airline VALUES ('PC', 'Air Fiji')
INSERT INTO airline VALUES ('AF', 'Air France')
INSERT INTO airline VALUES ('D7', 'AirAsia X')
INSERT INTO airline VALUES ('AI', 'Air India')
INSERT INTO airline VALUES ('IX', 'Air India Express')
INSERT INTO airline VALUES ('I5', 'Air Asia India')
INSERT INTO airline VALUES ('QP', 'Akasa Air')
INSERT INTO airline VALUES ('OB', 'Astrakhan Airlines')
INSERT INTO airline VALUES ('OS', 'Austrian Airlines')
INSERT INTO airline VALUES ('BA', 'British Airways')
INSERT INTO airline VALUES ('DE', 'Condor Airlines')
INSERT INTO airline VALUES ('T3', 'Eastern Airways')
INSERT INTO airline VALUES ('EK', 'Emirates')
INSERT INTO airline VALUES ('EY', 'Etihad Airways')
INSERT INTO airline VALUES ('AY', 'Finnair')
INSERT INTO airline VALUES ('TR', 'Fly Scoot')
INSERT INTO airline VALUES ('FZ', 'flydubai')
INSERT INTO airline VALUES ('G8', 'Go first')
INSERT INTO airline VALUES ('GF', 'Gulf Air')
INSERT INTO airline VALUES ('6E', 'Indigo')
INSERT INTO airline VALUES ('QZ', 'Indonesia AirAsia')
INSERT INTO airline VALUES ('J9', 'Jazeera Airways')
INSERT INTO airline VALUES ('3K', 'Jetstar Asia')
INSERT INTO airline VALUES ('KL', 'KLM Airlines')
INSERT INTO airline VALUES ('KU', 'Kuwait Airways')
INSERT INTO airline VALUES ('LH', 'Lufthansa')
INSERT INTO airline VALUES ('MH', 'Malaysia Airlines')
INSERT INTO airline VALUES ('TF', 'Malmö Aviation')
INSERT INTO airline VALUES ('XJ', 'Mesaba Airlines')
INSERT INTO airline VALUES ('WY', 'Oman Air')
INSERT INTO airline VALUES ('QR', 'Qatar Airways')
INSERT INTO airline VALUES ('SG', 'Spicejet')
INSERT INTO airline VALUES ('UL', 'SriLankan')
INSERT INTO airline VALUES ('XQ', 'SunExpress')
INSERT INTO airline VALUES ('FD', 'Thai AirAsia')
INSERT INTO airline VALUES ('TG', 'Thai Airways')
INSERT INTO airline VALUES ('MT', 'Thomas Cook Airlines')
INSERT INTO airline VALUES ('VS', 'Virgin Atlantic')
INSERT INTO airline VALUES ('UK', 'Vistara')
INSERT INTO airline VALUES ('VY', 'Vueling Airlines')
INSERT INTO airline VALUES ('WS', 'WestJet')

INSERT INTO airport(aCode, aName, loc) VALUES ('POM', 'Port Moresby Jacksons International Airport', 'Port Moresby, PG')
INSERT INTO airport(aCode, aName, loc) VALUES ('KEF', 'Keflavik International Airport', 'ReykjavAk, IS')
INSERT INTO airport(aCode, aName, loc) VALUES ('PRN', 'Pristina International Airport', 'Prishtina, XK')
INSERT INTO airport(aCode, aName, loc) VALUES ('YEG', 'Edmonton International Airport', 'Edmonton, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YHZ', 'Halifax / Stanfield International Airport', 'Halifax, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YOW', 'Ottawa Macdonald-Cartier International Airport', 'Ottawa, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YUL', 'Montreal / Pierre Elliott Trudeau International Airport', 'MontrA(c)al, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YVR', 'Vancouver International Airport', 'Vancouver, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YWG', 'Winnipeg / James Armstrong Richardson International Airport', 'Winnipeg, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YYC', 'Calgary International Airport', 'Calgary, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YYJ', 'Victoria International Airport', 'Victoria, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YYT', 'St. John''s International Airport', 'St. John''s, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('YYZ', 'Lester B. Pearson International Airport', 'Toronto, CA')
INSERT INTO airport(aCode, aName, loc) VALUES ('ALG', 'Houari Boumediene Airport', 'Algiers, DZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('OUA', 'Ouagadougou Airport', 'Ouagadougou, BF')
INSERT INTO airport(aCode, aName, loc) VALUES ('ACC', 'Kotoka International Airport', 'Accra, GH')
INSERT INTO airport(aCode, aName, loc) VALUES ('ABV', 'Nnamdi Azikiwe International Airport', 'Abuja, NG')
INSERT INTO airport(aCode, aName, loc) VALUES ('QUO', 'Akwa Ibom International Airport', 'Uyo, NG')
INSERT INTO airport(aCode, aName, loc) VALUES ('KAN', 'Mallam Aminu International Airport', 'Kano, NG')
INSERT INTO airport(aCode, aName, loc) VALUES ('LOS', 'Murtala Muhammed International Airport', 'Lagos, NG')
INSERT INTO airport(aCode, aName, loc) VALUES ('NIM', 'Diori Hamani International Airport', 'Niamey, NE')
INSERT INTO airport(aCode, aName, loc) VALUES ('TUN', 'Tunis Carthage International Airport', 'Tunis, TN')
INSERT INTO airport(aCode, aName, loc) VALUES ('BRU', 'Brussels Airport', 'Brussels, BE')
INSERT INTO airport(aCode, aName, loc) VALUES ('CRL', 'Brussels South Charleroi Airport', 'Brussels, BE')
INSERT INTO airport(aCode, aName, loc) VALUES ('LGG', 'Liege Airport', 'Liege, BE')
INSERT INTO airport(aCode, aName, loc) VALUES ('SXF', 'Berlin-Schonefeld Airport', 'Berlin, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('DRS', 'Dresden Airport', 'Dresden, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('FRA', 'Frankfurt am Main Airport', 'Frankfurt am Main, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('FMO', 'Muenster Osnabrueck Airport', 'MA 1/4nster, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('HAM', 'Hamburg Airport', 'Hamburg, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('CGN', 'Cologne Bonn Airport', 'Cologne, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('DUS', 'Dusseldorf Airport', 'DA 1/4sseldorf, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('MUC', 'Munich Airport', 'Munich, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('NUE', 'Nuremberg Airport', 'Nuremberg, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('LEJ', 'Leipzig/Halle Airport', 'Leipzig, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('STR', 'Stuttgart Airport', 'Stuttgart, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('TXL', 'Berlin-Tegel Airport', 'Berlin, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('HAJ', 'Hannover Airport', 'Hannover, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('BRE', 'Bremen Airport', 'Bremen, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('DTM', 'Dortmund Airport', 'Dortmund, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('FKB', 'Karlsruhe Baden-Baden Airport', 'Baden-Baden, DE')
INSERT INTO airport(aCode, aName, loc) VALUES ('TLL', 'Lennart Meri Tallinn Airport', 'Tallinn, EE')
INSERT INTO airport(aCode, aName, loc) VALUES ('HEL', 'Helsinki Vantaa Airport', 'Helsinki, FI')
INSERT INTO airport(aCode, aName, loc) VALUES ('BFS', 'Belfast International Airport', 'Belfast, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('BHD', 'George Best Belfast City Airport', 'Belfast, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('BHX', 'Birmingham International Airport', 'Birmingham, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('MAN', 'Manchester Airport', 'Manchester, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('DSA', 'Robin Hood Doncaster Sheffield Airport', 'Doncaster, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('CWL', 'Cardiff International Airport', 'Cardiff, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('BRS', 'Bristol Airport', 'Bristol, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('LPL', 'Liverpool John Lennon Airport', 'Liverpool, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('LTN', 'London Luton Airport', 'London, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('BOH', 'Bournemouth Airport', 'Bournemouth, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('SOU', 'Southampton Airport', 'Southampton, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('LGW', 'London Gatwick Airport', 'London, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('LHR', 'London Heathrow Airport', 'London, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('LBA', 'Leeds Bradford Airport', 'Leeds, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('NCL', 'Newcastle Airport', 'Newcastle, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('EMA', 'East Midlands Airport', 'Nottingham, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('ABZ', 'Aberdeen Dyce Airport', 'Aberdeen, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('GLA', 'Glasgow International Airport', 'Glasgow, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('EDI', 'Edinburgh Airport', 'Edinburgh, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('NWI', 'Norwich International Airport', 'Norwich, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('STN', 'London Stansted Airport', 'London, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('EXT', 'Exeter International Airport', 'Exeter, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('AMS', 'Amsterdam Airport Schiphol', 'Amsterdam, NL')
INSERT INTO airport(aCode, aName, loc) VALUES ('EIN', 'Eindhoven Airport', 'Eindhoven, NL')
INSERT INTO airport(aCode, aName, loc) VALUES ('ORK', 'Cork Airport', 'Cork, IE')
INSERT INTO airport(aCode, aName, loc) VALUES ('DUB', 'Dublin Airport', 'Dublin, IE')
INSERT INTO airport(aCode, aName, loc) VALUES ('SNN', 'Shannon Airport', 'Shannon, IE')
INSERT INTO airport(aCode, aName, loc) VALUES ('BLL', 'Billund Airport', 'Billund, DK')
INSERT INTO airport(aCode, aName, loc) VALUES ('CPH', 'Copenhagen Kastrup Airport', 'Copenhagen, DK')
INSERT INTO airport(aCode, aName, loc) VALUES ('AAL', 'Aalborg Airport', 'Aalborg, DK')
INSERT INTO airport(aCode, aName, loc) VALUES ('LUX', 'Luxembourg-Findel International Airport', 'Luxembourg, LU')
INSERT INTO airport(aCode, aName, loc) VALUES ('BOO', 'BodA, Airport', 'BodA,, NO')
INSERT INTO airport(aCode, aName, loc) VALUES ('BGO', 'Bergen Airport Flesland', 'Bergen, NO')
INSERT INTO airport(aCode, aName, loc) VALUES ('OSL', 'Oslo Gardermoen Airport', 'Oslo, NO')
INSERT INTO airport(aCode, aName, loc) VALUES ('TOS', 'TromsA, Airport', 'TromsA,, NO')
INSERT INTO airport(aCode, aName, loc) VALUES ('TRD', 'Trondheim Airport VA|rnes', 'Trondheim, NO')
INSERT INTO airport(aCode, aName, loc) VALUES ('SVG', 'Stavanger Airport Sola', 'Stavanger, NO')
INSERT INTO airport(aCode, aName, loc) VALUES ('GDN', 'Gdansk Lech Walesa Airport', 'GdaAsk, PL')
INSERT INTO airport(aCode, aName, loc) VALUES ('KRK', 'Krakow John Paul II International Airport', 'KrakA3w, PL')
INSERT INTO airport(aCode, aName, loc) VALUES ('KTW', 'Katowice International Airport', 'Katowice, PL')
INSERT INTO airport(aCode, aName, loc) VALUES ('WMI', 'Modlin Airport', 'Warsaw, PL')
INSERT INTO airport(aCode, aName, loc) VALUES ('POZ', 'Poznan-Lawica Airport', 'PoznaA, PL')
INSERT INTO airport(aCode, aName, loc) VALUES ('WAW', 'Warsaw Chopin Airport', 'Warsaw, PL')
INSERT INTO airport(aCode, aName, loc) VALUES ('WRO', 'Copernicus WrocAaw Airport', 'WrocAaw, PL')
INSERT INTO airport(aCode, aName, loc) VALUES ('GOT', 'Gothenburg-Landvetter Airport', 'Gothenburg, SE')
INSERT INTO airport(aCode, aName, loc) VALUES ('MMX', 'Malmo Sturup Airport', 'MalmAP, SE')
INSERT INTO airport(aCode, aName, loc) VALUES ('LLA', 'Lulea Airport', 'LuleAY=, SE')
INSERT INTO airport(aCode, aName, loc) VALUES ('ARN', 'Stockholm-Arlanda Airport', 'Stockholm, SE')
INSERT INTO airport(aCode, aName, loc) VALUES ('RIX', 'Riga International Airport', 'Riga, LV')
INSERT INTO airport(aCode, aName, loc) VALUES ('VNO', 'Vilnius International Airport', 'Vilnius, LT')
INSERT INTO airport(aCode, aName, loc) VALUES ('CPT', 'Cape Town International Airport', 'Cape Town, ZA')
INSERT INTO airport(aCode, aName, loc) VALUES ('GRJ', 'George Airport', 'George, ZA')
INSERT INTO airport(aCode, aName, loc) VALUES ('DUR', 'King Shaka International Airport', 'Durban, ZA')
INSERT INTO airport(aCode, aName, loc) VALUES ('JNB', 'OR Tambo International Airport', 'Johannesburg, ZA')
INSERT INTO airport(aCode, aName, loc) VALUES ('GBE', 'Sir Seretse Khama International Airport', 'Gaborone, BW')
INSERT INTO airport(aCode, aName, loc) VALUES ('SHO', 'King Mswati III International Airport', ', SZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('MRU', 'Sir Seewoosagur Ramgoolam International Airport', 'Port Louis, MU')
INSERT INTO airport(aCode, aName, loc) VALUES ('LUN', 'Kenneth Kaunda International Airport', 'Lusaka, ZM')
INSERT INTO airport(aCode, aName, loc) VALUES ('TNR', 'Ivato Airport', 'Antananarivo, MG')
INSERT INTO airport(aCode, aName, loc) VALUES ('LAD', 'Quatro de Fevereiro Airport', 'Luanda, AO')
INSERT INTO airport(aCode, aName, loc) VALUES ('MPM', 'Maputo Airport', 'Maputo, MZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('SEZ', 'Seychelles International Airport', 'Mahe Island, SC')
INSERT INTO airport(aCode, aName, loc) VALUES ('NDJ', 'N''Djamena International Airport', 'N''Djamena, TD')
INSERT INTO airport(aCode, aName, loc) VALUES ('HRE', 'Robert Gabriel Mugabe International Airport', 'Harare, ZW')
INSERT INTO airport(aCode, aName, loc) VALUES ('WDH', 'Hosea Kutako International Airport', 'Windhoek, NA')
INSERT INTO airport(aCode, aName, loc) VALUES ('FIH', 'Ndjili International Airport', 'Kinshasa, CD')
INSERT INTO airport(aCode, aName, loc) VALUES ('BKO', 'Modibo Keita International Airport', 'Bamako, ML')
INSERT INTO airport(aCode, aName, loc) VALUES ('SPC', 'La Palma Airport', 'Sta Cruz de la Palma, La Palma Island, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('LPA', 'Gran Canaria Airport', 'Gran Canaria Island, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('TFS', 'Tenerife South Airport', 'Tenerife Island, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('TFN', 'Tenerife Norte Airport', 'Tenerife Island, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('FNA', 'Lungi International Airport', 'Freetown, SL')
INSERT INTO airport(aCode, aName, loc) VALUES ('ROB', 'Roberts International Airport', 'Monrovia, LR')
INSERT INTO airport(aCode, aName, loc) VALUES ('CMN', 'Mohammed V International Airport', 'Casablanca, MA')
INSERT INTO airport(aCode, aName, loc) VALUES ('DSS', 'Blaise Diagne International Airport', 'Dakar, SN')
INSERT INTO airport(aCode, aName, loc) VALUES ('DKR', 'Leopold Sedar Senghor International Airport', 'Dakar, SN')
INSERT INTO airport(aCode, aName, loc) VALUES ('NKC', 'Nouakchott-Oumtounsy International Airport', 'Nouakchott, MR')
INSERT INTO airport(aCode, aName, loc) VALUES ('SID', 'Amilcar Cabral International Airport', 'Espargos, CV')
INSERT INTO airport(aCode, aName, loc) VALUES ('ADD', 'Addis Ababa Bole International Airport', 'Addis Ababa, ET')
INSERT INTO airport(aCode, aName, loc) VALUES ('HGA', 'Egal International Airport', 'Hargeisa, SO')
INSERT INTO airport(aCode, aName, loc) VALUES ('CAI', 'Cairo International Airport', 'Cairo, EG')
INSERT INTO airport(aCode, aName, loc) VALUES ('HRG', 'Hurghada International Airport', 'Hurghada, EG')
INSERT INTO airport(aCode, aName, loc) VALUES ('LXR', 'Luxor International Airport', 'Luxor, EG')
INSERT INTO airport(aCode, aName, loc) VALUES ('NBO', 'Jomo Kenyatta International Airport', 'Nairobi, KE')
INSERT INTO airport(aCode, aName, loc) VALUES ('MBA', 'Mombasa Moi International Airport', 'Mombasa, KE')
INSERT INTO airport(aCode, aName, loc) VALUES ('TIP', 'Tripoli International Airport', 'Tripoli, LY')
INSERT INTO airport(aCode, aName, loc) VALUES ('KGL', 'Kigali International Airport', 'Kigali, RW')
INSERT INTO airport(aCode, aName, loc) VALUES ('JUB', 'Juba International Airport', 'Juba, SS')
INSERT INTO airport(aCode, aName, loc) VALUES ('KRT', 'Khartoum International Airport', 'Khartoum, SD')
INSERT INTO airport(aCode, aName, loc) VALUES ('DAR', 'Julius Nyerere International Airport', 'Dar es Salaam, TZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('ZNZ', 'Abeid Amani Karume International Airport', 'Zanzibar, TZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('EBB', 'Entebbe International Airport', 'Kampala, UG')
INSERT INTO airport(aCode, aName, loc) VALUES ('AAP', 'Aji Pangeran Tumenggung Pranoto International Airport', 'Samarinda, ID')
INSERT INTO airport(aCode, aName, loc) VALUES ('ABQ', 'Albuquerque International Sunport', 'Albuquerque, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ADW', 'Joint Base Andrews', 'Camp Springs, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('AFW', 'Fort Worth Alliance Airport', 'Fort Worth, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('AGS', 'Augusta Regional At Bush Field', 'Augusta, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('AMA', 'Rick Husband Amarillo International Airport', 'Amarillo, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ATL', 'Hartsfield Jackson Atlanta International Airport', 'Atlanta, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('AUS', 'Austin Bergstrom International Airport', 'Austin, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('AVL', 'Asheville Regional Airport', 'Asheville, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BDL', 'Bradley International Airport', 'Hartford, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BFI', 'Boeing Field King County International Airport', 'Seattle, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BGR', 'Bangor International Airport', 'Bangor, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BHM', 'Birmingham-Shuttlesworth International Airport', 'Birmingham, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BIL', 'Billings Logan International Airport', 'Billings, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BLV', 'Scott AFB/Midamerica Airport', 'Belleville, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BMI', 'Central Illinois Regional Airport at Bloomington-Normal', 'Bloomington/Normal, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BNA', 'Nashville International Airport', 'Nashville, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BOI', 'Boise Air Terminal/Gowen Field', 'Boise, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BOS', 'General Edward Lawrence Logan International Airport', 'Boston, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BUF', 'Buffalo Niagara International Airport', 'Buffalo, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('BWI', 'Baltimore/Washington International Thurgood Marshall Airport', 'Baltimore, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CAE', 'Columbia Metropolitan Airport', 'Columbia, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CHA', 'Lovell Field', 'Chattanooga, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CHS', 'Charleston Air Force Base-International Airport', 'Charleston, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CID', 'The Eastern Iowa Airport', 'Cedar Rapids, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CLE', 'Cleveland Hopkins International Airport', 'Cleveland, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CLT', 'Charlotte Douglas International Airport', 'Charlotte, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CMH', 'John Glenn Columbus International Airport', 'Columbus, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('COS', 'City of Colorado Springs Municipal Airport', 'Colorado Springs, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CRP', 'Corpus Christi International Airport', 'Corpus Christi, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CRW', 'Yeager Airport', 'Charleston, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('CVG', 'Cincinnati Northern Kentucky International Airport', 'Cincinnati / Covington, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DAB', 'Daytona Beach International Airport', 'Daytona Beach, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DAL', 'Dallas Love Field', 'Dallas, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DAY', 'James M Cox Dayton International Airport', 'Dayton, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DBQ', 'Dubuque Regional Airport', 'Dubuque, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DCA', 'Ronald Reagan Washington National Airport', 'Washington, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DEN', 'Denver International Airport', 'Denver, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DFW', 'Dallas Fort Worth International Airport', 'Dallas-Fort Worth, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DLF', 'DLF Airport', 'Del Rio, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DLH', 'Duluth International Airport', 'Duluth, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DSM', 'Des Moines International Airport', 'Des Moines, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('DTW', 'Detroit Metropolitan Wayne County Airport', 'Detroit, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ERI', 'Erie International Tom Ridge Field', 'Erie, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('EWR', 'Newark Liberty International Airport', 'Newark, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('FLL', 'Fort Lauderdale Hollywood International Airport', 'Fort Lauderdale, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('FSM', 'Fort Smith Regional Airport', 'Fort Smith, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('FTW', 'Fort Worth Meacham International Airport', 'Fort Worth, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('FWA', 'Fort Wayne International Airport', 'Fort Wayne, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('GEG', 'Spokane International Airport', 'Spokane, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('GPT', 'Gulfport Biloxi International Airport', 'Gulfport, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('GRB', 'Austin Straubel International Airport', 'Green Bay, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('GSO', 'Piedmont Triad International Airport', 'Greensboro, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('GSP', 'Greenville Spartanburg International Airport', 'Greenville, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('HIB', 'Range Regional Airport', 'Hibbing, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('HOU', 'William P Hobby Airport', 'Houston, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('HSV', 'Huntsville International Carl T Jones Field', 'Huntsville, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('HTS', 'Tri-State/Milton J. Ferguson Field', 'Huntington, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('IAD', 'Washington Dulles International Airport', 'Washington, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('IAH', 'George Bush Intercontinental Houston Airport', 'Houston, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ICT', 'Wichita Eisenhower National Airport', 'Wichita, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('IND', 'Indianapolis International Airport', 'Indianapolis, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('JAN', 'Jackson-Medgar Wiley Evers International Airport', 'Jackson, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('JAX', 'Jacksonville International Airport', 'Jacksonville, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('JFK', 'John F Kennedy International Airport', 'New York, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('JLN', 'Joplin Regional Airport', 'Joplin, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('LAS', 'McCarran International Airport', 'Las Vegas, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('LAX', 'Los Angeles International Airport', 'Los Angeles, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('LBB', 'Lubbock Preston Smith International Airport', 'Lubbock, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('LCK', 'Rickenbacker International Airport', 'Columbus, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('LEX', 'Blue Grass Airport', 'Lexington, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('LFT', 'Lafayette Regional Airport', 'Lafayette, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('LGA', 'La Guardia Airport', 'New York, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('LIT', 'Bill & Hillary Clinton National Airport/Adams Field', 'Little Rock, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MBS', 'MBS International Airport', 'Saginaw, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MCI', 'Kansas City International Airport', 'Kansas City, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MCO', 'Orlando International Airport', 'Orlando, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MDW', 'Chicago Midway International Airport', 'Chicago, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MEM', 'Memphis International Airport', 'Memphis, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MGM', 'Montgomery Regional (Dannelly Field) Airport', 'Montgomery, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MHT', 'Manchester-Boston Regional Airport', 'Manchester, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MIA', 'Miami International Airport', 'Miami, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MKE', 'General Mitchell International Airport', 'Milwaukee, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MLI', 'Quad City International Airport', 'Moline, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MLU', 'Monroe Regional Airport', 'Monroe, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MOB', 'Mobile Regional Airport', 'Mobile, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MSN', 'Dane County Regional Truax Field', 'Madison, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MSP', 'Minneapolis-St Paul International/Wold-Chamberlain Airport', 'Minneapolis, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('MSY', 'Louis Armstrong New Orleans International Airport', 'New Orleans, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('OAK', 'Metropolitan Oakland International Airport', 'Oakland, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('OKC', 'Will Rogers World Airport', 'Oklahoma City, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('OMA', 'Eppley Airfield', 'Omaha, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ONT', 'Ontario International Airport', 'Ontario, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ORD', 'Chicago O''Hare International Airport', 'Chicago, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ORF', 'Norfolk International Airport', 'Norfolk, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PBI', 'Palm Beach International Airport', 'West Palm Beach, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PDX', 'Portland International Airport', 'Portland, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PHF', 'Newport News Williamsburg International Airport', 'Newport News, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PHL', 'Philadelphia International Airport', 'Philadelphia, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PIA', 'General Wayne A. Downing Peoria International Airport', 'Peoria, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PIT', 'Pittsburgh International Airport', 'Pittsburgh, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PVD', 'Theodore Francis Green State Airport', 'Providence, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('PWM', 'Portland International Jetport', 'Portland, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('RDU', 'Raleigh Durham International Airport', 'Raleigh/Durham, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('RFD', 'Chicago Rockford International Airport', 'Chicago/Rockford, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('RIC', 'Richmond International Airport', 'Richmond, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('RNO', 'Reno Tahoe International Airport', 'Reno, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ROA', 'RoanokeaBlacksburg Regional Airport', 'Roanoke, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ROC', 'Greater Rochester International Airport', 'Rochester, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('RST', 'Rochester International Airport', 'Rochester, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('RSW', 'Southwest Florida International Airport', 'Fort Myers, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SAN', 'San Diego International Airport', 'San Diego, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SAT', 'San Antonio International Airport', 'San Antonio, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SAV', 'Savannah Hilton Head International Airport', 'Savannah, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SBN', 'South Bend Regional Airport', 'South Bend, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SDF', 'Louisville Muhammad Ali International Airport', 'Louisville, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SEA', 'Seattle Tacoma International Airport', 'Seattle, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SFB', 'Orlando Sanford International Airport', 'Orlando, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SFO', 'San Francisco International Airport', 'San Francisco, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SGF', 'Springfield Branson National Airport', 'Springfield, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SJC', 'Norman Y. Mineta San Jose International Airport', 'San Jose, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SLC', 'Salt Lake City International Airport', 'Salt Lake City, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SMF', 'Sacramento International Airport', 'Sacramento, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SNA', 'John Wayne Airport-Orange County Airport', 'Santa Ana, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SPI', 'Abraham Lincoln Capital Airport', 'Springfield, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SPS', 'Sheppard Air Force Base-Wichita Falls Municipal Airport', 'Wichita Falls, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SRQ', 'Sarasota Bradenton International Airport', 'Sarasota/Bradenton, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('STL', 'St Louis Lambert International Airport', 'St Louis, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SUS', 'Spirit of St Louis Airport', 'St Louis, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SUX', 'Sioux Gateway Airport/Brigadier General Bud Day Field', 'Sioux City, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('SYR', 'Syracuse Hancock International Airport', 'Syracuse, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('TLH', 'Tallahassee Regional Airport', 'Tallahassee, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('TOL', 'Toledo Express Airport', 'Toledo, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('TPA', 'Tampa International Airport', 'Tampa, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('TRI', 'Tri-Cities Regional TN/VA Airport', 'Bristol/Johnson/Kingsport, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('TUL', 'Tulsa International Airport', 'Tulsa, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('TUS', 'Tucson International Airport / Morris Air National Guard Base', 'Tucson, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('TYS', 'McGhee Tyson Airport', 'Knoxville, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('VPS', 'Destin-Ft Walton Beach Airport', 'Valparaiso, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('TIA', 'Tirana International Airport Mother Teresa', 'Tirana, AL')
INSERT INTO airport(aCode, aName, loc) VALUES ('BOJ', 'Burgas Airport', 'Burgas, BG')
INSERT INTO airport(aCode, aName, loc) VALUES ('SOF', 'Sofia Airport', 'Sofia, BG')
INSERT INTO airport(aCode, aName, loc) VALUES ('VAR', 'Varna Airport', 'Varna, BG')
INSERT INTO airport(aCode, aName, loc) VALUES ('LCA', 'Larnaca International Airport', 'Larnarca, CY')
INSERT INTO airport(aCode, aName, loc) VALUES ('PFO', 'Paphos International Airport', 'Paphos, CY')
INSERT INTO airport(aCode, aName, loc) VALUES ('AKT', 'RAF Akrotiri', 'Akrotiri, GB')
INSERT INTO airport(aCode, aName, loc) VALUES ('ZAG', 'Zagreb Airport', 'Zagreb, HR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ALC', 'Alicante International Airport', 'Alicante, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('BCN', 'Barcelona International Airport', 'Barcelona, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('MAD', 'Adolfo SuA!rez MadridaBarajas Airport', 'Madrid, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('AGP', 'MA!laga Airport', 'MA!laga, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('PMI', 'Palma De Mallorca Airport', 'Palma De Mallorca, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('SCQ', 'Santiago de Compostela Airport', 'Santiago de Compostela, ES')
INSERT INTO airport(aCode, aName, loc) VALUES ('BOD', 'Bordeaux-MA(c)rignac Airport', 'Bordeaux/MA(c)rignac, FR')
INSERT INTO airport(aCode, aName, loc) VALUES ('TLS', 'Toulouse-Blagnac Airport', 'Toulouse/Blagnac, FR')
INSERT INTO airport(aCode, aName, loc) VALUES ('LYS', 'Lyon Saint-ExupA(c)ry Airport', 'Lyon, FR')
INSERT INTO airport(aCode, aName, loc) VALUES ('MRS', 'Marseille Provence Airport', 'Marseille, FR')
INSERT INTO airport(aCode, aName, loc) VALUES ('NCE', 'Nice Cote d''Azur Airport', 'Nice, FR')
INSERT INTO airport(aCode, aName, loc) VALUES ('CDG', 'Charles de Gaulle International Airport', 'Paris, FR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ORY', 'Paris-Orly Airport', 'Paris, FR')
INSERT INTO airport(aCode, aName, loc) VALUES ('BSL', 'EuroAirport Basel-Mulhouse-Freiburg Airport', 'BAC/le/Mulhouse, FR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ATH', 'Eleftherios Venizelos International Airport', 'Athens, GR')
INSERT INTO airport(aCode, aName, loc) VALUES ('HER', 'Heraklion International Nikos Kazantzakis Airport', 'Heraklion, GR')
INSERT INTO airport(aCode, aName, loc) VALUES ('SKG', 'Thessaloniki Macedonia International Airport', 'Thessaloniki, GR')
INSERT INTO airport(aCode, aName, loc) VALUES ('BUD', 'Budapest Liszt Ferenc International Airport', 'Budapest, HU')
INSERT INTO airport(aCode, aName, loc) VALUES ('BRI', 'Bari Karol Wojtyla Airport', 'Bari, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('CTA', 'Catania-Fontanarossa Airport', 'Catania, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('PMO', 'FalconeaBorsellino Airport', 'Palermo, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('CAG', 'Cagliari Elmas Airport', 'Cagliari, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('MXP', 'Malpensa International Airport', 'Milan, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('BGY', 'Milan Bergamo Airport', 'Bergamo, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('TRN', 'Turin Airport', 'Torino, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('GOA', 'Genoa Cristoforo Colombo Airport', 'Genova, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('LIN', 'Milano Linate Airport', 'Milan, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('BLQ', 'Bologna Guglielmo Marconi Airport', 'Bologna, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('TSF', 'Treviso-Sant''Angelo Airport', 'Treviso, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('VRN', 'Verona Villafranca Airport', 'Verona, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('VCE', 'Venice Marco Polo Airport', 'Venice, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('CIA', 'CiampinoaG. B. Pastine International Airport', 'Rome, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('FCO', 'Leonardo da Vinci-Fiumicino Airport', 'Rome, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('NAP', 'Naples International Airport', 'NA!poli, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('PSA', 'Pisa International Airport', 'Pisa, IT')
INSERT INTO airport(aCode, aName, loc) VALUES ('LJU', 'Ljubljana JoA 3/4e PuAnik Airport', 'Ljubljana, SI')
INSERT INTO airport(aCode, aName, loc) VALUES ('PRG', 'Vaclav Havel Airport Prague', 'Prague, CZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('TLV', 'Ben Gurion International Airport', 'Tel Aviv, IL')
INSERT INTO airport(aCode, aName, loc) VALUES ('VDA', 'Ovda International Airport', 'Eilat, IL')
INSERT INTO airport(aCode, aName, loc) VALUES ('MLA', 'Malta International Airport', 'Valletta, MT')
INSERT INTO airport(aCode, aName, loc) VALUES ('VIE', 'Vienna International Airport', 'Vienna, AT')
INSERT INTO airport(aCode, aName, loc) VALUES ('FAO', 'Faro Airport', 'Faro, PT')
INSERT INTO airport(aCode, aName, loc) VALUES ('TER', 'Lajes Airport', 'Praia da VitA3ria, PT')
INSERT INTO airport(aCode, aName, loc) VALUES ('PDL', 'Joao Paulo II Airport', 'Ponta Delgada, PT')
INSERT INTO airport(aCode, aName, loc) VALUES ('OPO', 'Francisco Sa Carneiro Airport', 'Porto, PT')
INSERT INTO airport(aCode, aName, loc) VALUES ('LIS', 'Humberto Delgado Airport (Lisbon Portela Airport)', 'Lisbon, PT')
INSERT INTO airport(aCode, aName, loc) VALUES ('SJJ', 'Sarajevo International Airport', 'Sarajevo, BA')
INSERT INTO airport(aCode, aName, loc) VALUES ('OTP', 'Henri CoandA International Airport', 'Bucharest, RO')
INSERT INTO airport(aCode, aName, loc) VALUES ('GVA', 'Geneva Cointrin International Airport', 'Geneva, CH')
INSERT INTO airport(aCode, aName, loc) VALUES ('ZRH', 'Zurich Airport', 'Zurich, CH')
INSERT INTO airport(aCode, aName, loc) VALUES ('ESB', 'Esenboga International Airport', 'Ankara, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ADA', 'Adana Airport', 'Adana, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('AYT', 'Antalya International Airport', 'Antalya, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('GZT', 'Gaziantep International Airport', 'Gaziantep, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ISL', 'AtatA 1/4rk International Airport', 'Istanbul, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ADB', 'Adnan Menderes International Airport', 'Adegzmir, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('DLM', 'Dalaman International Airport', 'Dalaman, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ERZ', 'Erzurum International Airport', 'Erzurum, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('TZX', 'Trabzon International Airport', 'Trabzon, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ISE', 'SA 1/4leyman Demirel International Airport', 'Isparta, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('BJV', 'Milas Bodrum International Airport', 'Bodrum, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('SAW', 'Sabiha GAPkASSen International Airport', 'Istanbul, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('IST', 'Istanbul Airport', 'Istanbul, TR')
INSERT INTO airport(aCode, aName, loc) VALUES ('SKP', 'Skopje International Airport', 'Skopje, MK')
INSERT INTO airport(aCode, aName, loc) VALUES ('BEG', 'Belgrade Nikola Tesla Airport', 'Belgrade, RS')
INSERT INTO airport(aCode, aName, loc) VALUES ('TGD', 'Podgorica Airport', 'Podgorica, ME')
INSERT INTO airport(aCode, aName, loc) VALUES ('BTS', 'M. R. A tefA!nik Airport', 'Bratislava, SK')
INSERT INTO airport(aCode, aName, loc) VALUES ('PUJ', 'Punta Cana International Airport', 'Punta Cana, DO')
INSERT INTO airport(aCode, aName, loc) VALUES ('SDQ', 'Las AmA(c)ricas International Airport', 'Santo Domingo, DO')
INSERT INTO airport(aCode, aName, loc) VALUES ('GUA', 'La Aurora Airport', 'Guatemala City, GT')
INSERT INTO airport(aCode, aName, loc) VALUES ('KIN', 'Norman Manley International Airport', 'Kingston, JM')
INSERT INTO airport(aCode, aName, loc) VALUES ('ACA', 'General Juan N Alvarez International Airport', 'Acapulco, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('GDL', 'Don Miguel Hidalgo Y Costilla International Airport', 'Guadalajara, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('HMO', 'General Ignacio P. Garcia International Airport', 'Hermosillo, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('MEX', 'Licenciado Benito Juarez International Airport', 'Mexico City, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('MTY', 'General Mariano Escobedo International Airport', 'Monterrey, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('PVR', 'Licenciado Gustavo DAaz Ordaz International Airport', 'Puerto Vallarta, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('SJD', 'Los Cabos International Airport', 'San JosA(c) del Cabo, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('TIJ', 'General Abelardo L. RodrAguez International Airport', 'Tijuana, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('CUN', 'CancAon International Airport', 'CancAon, MX')
INSERT INTO airport(aCode, aName, loc) VALUES ('PTY', 'Tocumen International Airport', 'Tocumen, PA')
INSERT INTO airport(aCode, aName, loc) VALUES ('LIR', 'Daniel Oduber Quiros International Airport', 'Liberia, CR')
INSERT INTO airport(aCode, aName, loc) VALUES ('SAL', 'MonseA+-or Ascar Arnulfo Romero International Airport', 'San Salvador (San Luis Talpa), SV')
INSERT INTO airport(aCode, aName, loc) VALUES ('HAV', 'JosA(c) MartA International Airport', 'Havana, CU')
INSERT INTO airport(aCode, aName, loc) VALUES ('VRA', 'Juan Gualberto Gomez International Airport', 'Varadero, CU')
INSERT INTO airport(aCode, aName, loc) VALUES ('GCM', 'Owen Roberts International Airport', 'Georgetown, KY')
INSERT INTO airport(aCode, aName, loc) VALUES ('NAS', 'Lynden Pindling International Airport', 'Nassau, BS')
INSERT INTO airport(aCode, aName, loc) VALUES ('BZE', 'Philip S. W. Goldson International Airport', 'Belize City, BZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('RAR', 'Rarotonga International Airport', 'Avarua, CK')
INSERT INTO airport(aCode, aName, loc) VALUES ('PPT', 'Faa''a International Airport', 'Papeete, PF')
INSERT INTO airport(aCode, aName, loc) VALUES ('AKL', 'Auckland International Airport', 'Auckland, NZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('CHC', 'Christchurch International Airport', 'Christchurch, NZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('WLG', 'Wellington International Airport', 'Wellington, NZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('BAH', 'Bahrain International Airport', 'Manama, BH')
INSERT INTO airport(aCode, aName, loc) VALUES ('DMM', 'King Fahd International Airport', 'Ad Dammam, SA')
INSERT INTO airport(aCode, aName, loc) VALUES ('JED', 'King Abdulaziz International Airport', 'Jeddah, SA')
INSERT INTO airport(aCode, aName, loc) VALUES ('MED', 'Prince Mohammad Bin Abdulaziz Airport', 'Medina, SA')
INSERT INTO airport(aCode, aName, loc) VALUES ('RUH', 'King Khaled International Airport', 'Riyadh, SA')
INSERT INTO airport(aCode, aName, loc) VALUES ('IKA', 'Imam Khomeini International Airport', 'Tehran, IR')
INSERT INTO airport(aCode, aName, loc) VALUES ('THR', 'Mehrabad International Airport', 'Tehran, IR')
INSERT INTO airport(aCode, aName, loc) VALUES ('MHD', 'Mashhad International Airport', 'Mashhad, IR')
INSERT INTO airport(aCode, aName, loc) VALUES ('SYZ', 'Shiraz Shahid Dastghaib International Airport', 'Shiraz, IR')
INSERT INTO airport(aCode, aName, loc) VALUES ('TBZ', 'Tabriz International Airport', 'Tabriz, IR')
INSERT INTO airport(aCode, aName, loc) VALUES ('AMM', 'Queen Alia International Airport', 'Amman, JO')
INSERT INTO airport(aCode, aName, loc) VALUES ('KWI', 'Kuwait International Airport', 'Kuwait City, KW')
INSERT INTO airport(aCode, aName, loc) VALUES ('BEY', 'Beirut Rafic Hariri International Airport', 'Beirut, LB')
INSERT INTO airport(aCode, aName, loc) VALUES ('DQM', 'Duqm International Airport', 'Duqm, OM')
INSERT INTO airport(aCode, aName, loc) VALUES ('MNH', 'Rustaq Airport', 'Al Masna''ah, OM')
INSERT INTO airport(aCode, aName, loc) VALUES ('AUH', 'Abu Dhabi International Airport', 'Abu Dhabi, AE')
INSERT INTO airport(aCode, aName, loc) VALUES ('DXB', 'Dubai International Airport', 'Dubai, AE')
INSERT INTO airport(aCode, aName, loc) VALUES ('DWC', 'Al Maktoum International Airport', 'Jebel Ali, AE')
INSERT INTO airport(aCode, aName, loc) VALUES ('SHJ', 'Sharjah International Airport', 'Sharjah, AE')
INSERT INTO airport(aCode, aName, loc) VALUES ('MCT', 'Muscat International Airport', 'Muscat, OM')
INSERT INTO airport(aCode, aName, loc) VALUES ('ISB', 'Islamabad International Airport', 'Islamabad, PK')
INSERT INTO airport(aCode, aName, loc) VALUES ('SKT', 'Sialkot Airport', 'Sialkot, PK')
INSERT INTO airport(aCode, aName, loc) VALUES ('BGW', 'Baghdad International Airport', 'Baghdad, IQ')
INSERT INTO airport(aCode, aName, loc) VALUES ('BSR', 'Basrah International Airport', 'Basrah, IQ')
INSERT INTO airport(aCode, aName, loc) VALUES ('ALP', 'Aleppo International Airport', 'Aleppo, SY')
INSERT INTO airport(aCode, aName, loc) VALUES ('DAM', 'Damascus International Airport', 'Damascus, SY')
INSERT INTO airport(aCode, aName, loc) VALUES ('LTK', 'Bassel Al-Assad International Airport', 'Latakia, SY')
INSERT INTO airport(aCode, aName, loc) VALUES ('DOH', 'Hamad International Airport', 'Doha, QA')
INSERT INTO airport(aCode, aName, loc) VALUES ('FAI', 'Fairbanks International Airport', 'Fairbanks, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('ANC', 'Ted Stevens Anchorage International Airport', 'Anchorage, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('GUM', 'Antonio B. Won Pat International Airport', 'HagAY=tA+-a, Guam International Airport, GU')
INSERT INTO airport(aCode, aName, loc) VALUES ('CGY', 'Laguindingan Airport', 'Cagayan de Oro City, PH')
INSERT INTO airport(aCode, aName, loc) VALUES ('HNL', 'Daniel K Inouye International Airport', 'Honolulu, US')
INSERT INTO airport(aCode, aName, loc) VALUES ('KNH', 'Kinmen Airport', 'Shang-I, TW')
INSERT INTO airport(aCode, aName, loc) VALUES ('KHH', 'Kaohsiung International Airport', 'Kaohsiung City, TW')
INSERT INTO airport(aCode, aName, loc) VALUES ('TPE', 'Taiwan Taoyuan International Airport', 'Taipei, TW')
INSERT INTO airport(aCode, aName, loc) VALUES ('NRT', 'Narita International Airport', 'Tokyo / Narita, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('KIX', 'Kansai International Airport', 'Osaka, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('CTS', 'New Chitose Airport', 'Chitose / Tomakomai, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('FUK', 'Fukuoka Airport', 'Fukuoka, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('KOJ', 'Kagoshima Airport', 'Kagoshima, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('NGO', 'Chubu Centrair International Airport', 'Tokoname, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('FSZ', 'Mt. Fuji Shizuoka Airport', 'Makinohara / Shimada, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('ITM', 'Osaka International Airport', 'Osaka, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('HND', 'Tokyo Haneda International Airport', 'Ota, Tokyo, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('MWX', 'Muan International Airport', 'Piseo-ri (Muan), KR')
INSERT INTO airport(aCode, aName, loc) VALUES ('CJU', 'Jeju International Airport', 'Jeju City, KR')
INSERT INTO airport(aCode, aName, loc) VALUES ('PUS', 'Gimhae International Airport', 'Busan, KR')
INSERT INTO airport(aCode, aName, loc) VALUES ('ICN', 'Incheon International Airport', 'Seoul, KR')
INSERT INTO airport(aCode, aName, loc) VALUES ('GMP', 'Gimpo International Airport', 'Seoul, KR')
INSERT INTO airport(aCode, aName, loc) VALUES ('OKA', 'Naha Airport', 'Naha, JP')
INSERT INTO airport(aCode, aName, loc) VALUES ('CRK', 'Diosdado Macapagal International Airport', 'Angeles/Mabalacat, PH')
INSERT INTO airport(aCode, aName, loc) VALUES ('MNL', 'Ninoy Aquino International Airport', 'Pasay / ParaA+-aque, Metro Manila, PH')
INSERT INTO airport(aCode, aName, loc) VALUES ('DVO', 'Francisco Bangoy International Airport', 'Davao City, PH')
INSERT INTO airport(aCode, aName, loc) VALUES ('CEB', 'Mactan Cebu International Airport', 'Lapu-Lapu City, PH')
INSERT INTO airport(aCode, aName, loc) VALUES ('GRV', 'Grozny North Airport', 'Grozny, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('EZE', 'Ministro Pistarini International Airport', 'Buenos Aires, AR')
INSERT INTO airport(aCode, aName, loc) VALUES ('BEL', 'Val de Cans/Julio Cezar Ribeiro International Airport', 'BelA(c)m, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('BSB', 'Presidente Juscelino Kubitschek International Airport', 'BrasAlia, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('CNF', 'Tancredo Neves International Airport', 'Belo Horizonte, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('CWB', 'Afonso Pena Airport', 'Curitiba, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('MAO', 'Eduardo Gomes International Airport', 'Manaus, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('FLN', 'Hercilio Luz International Airport', 'FlorianA3polis, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('GIG', 'Rio Galeao - Tom Jobim International Airport', 'Rio De Janeiro, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('GRU', 'Guarulhos - Governador AndrA(c) Franco Montoro International Airport', 'SAPSo Paulo, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('NAT', 'Governador AluAzio Alves International Airport', 'Natal, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('CGH', 'Congonhas Airport', 'SAPSo Paulo, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('SSA', 'Deputado Luiz Eduardo MagalhAPSes International Airport', 'Salvador, BR')
INSERT INTO airport(aCode, aName, loc) VALUES ('SCL', 'Comodoro Arturo Merino BenAtez International Airport', 'Santiago, CL')
INSERT INTO airport(aCode, aName, loc) VALUES ('LTX', 'Cotopaxi International Airport', 'Latacunga, EC')
INSERT INTO airport(aCode, aName, loc) VALUES ('UIO', 'Mariscal Sucre International Airport', 'Quito, EC')
INSERT INTO airport(aCode, aName, loc) VALUES ('BOG', 'El Dorado International Airport', 'Bogota, CO')
INSERT INTO airport(aCode, aName, loc) VALUES ('VVI', 'Viru Viru International Airport', 'Santa Cruz, BO')
INSERT INTO airport(aCode, aName, loc) VALUES ('LIM', 'Jorge ChA!vez International Airport', 'Lima, PE')
INSERT INTO airport(aCode, aName, loc) VALUES ('CUZ', 'Alejandro Velasco Astete International Airport', 'Cusco, PE')
INSERT INTO airport(aCode, aName, loc) VALUES ('MVD', 'Carrasco International /General C L Berisso Airport', 'Montevideo, UY')
INSERT INTO airport(aCode, aName, loc) VALUES ('BLA', 'General JosA(c) Antonio Anzoategui International Airport', 'Barcelona, VE')
INSERT INTO airport(aCode, aName, loc) VALUES ('CCS', 'SimA3n BolAvar International Airport', 'Caracas, VE')
INSERT INTO airport(aCode, aName, loc) VALUES ('PTP', 'Pointe-A -Pitre Le Raizet', 'Pointe-A -Pitre, GP')
INSERT INTO airport(aCode, aName, loc) VALUES ('SJU', 'Luis Munoz Marin International Airport', 'San Juan, PR')
INSERT INTO airport(aCode, aName, loc) VALUES ('NBE', 'Enfidha - Hammamet International Airport', 'Enfidha, TN')
INSERT INTO airport(aCode, aName, loc) VALUES ('SXM', 'Princess Juliana International Airport', 'Saint Martin, SX')
INSERT INTO airport(aCode, aName, loc) VALUES ('ALA', 'Almaty Airport', 'Almaty, KZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('TSE', 'Astana International Airport', 'Astana, KZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('FRU', 'Manas International Airport', 'Bishkek, KG')
INSERT INTO airport(aCode, aName, loc) VALUES ('KGF', 'Sary-Arka Airport', 'Karaganda, KZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('GYD', 'Heydar Aliyev International Airport', 'Baku, AZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('EVN', 'Zvartnots International Airport', 'Yerevan, AM')
INSERT INTO airport(aCode, aName, loc) VALUES ('TBS', 'Tbilisi International Airport', 'Tbilisi, GE')
INSERT INTO airport(aCode, aName, loc) VALUES ('KHV', 'Khabarovsk-Novy Airport', 'Khabarovsk, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('KBP', 'Boryspil International Airport', 'Kiev, UA')
INSERT INTO airport(aCode, aName, loc) VALUES ('SIP', 'Simferopol International Airport', 'Simferopol, UA')
INSERT INTO airport(aCode, aName, loc) VALUES ('HRK', 'Kharkiv International Airport', 'Kharkiv, UA')
INSERT INTO airport(aCode, aName, loc) VALUES ('ODS', 'Odessa International Airport', 'Odessa, UA')
INSERT INTO airport(aCode, aName, loc) VALUES ('LED', 'Pulkovo Airport', 'St. Petersburg, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('MSQ', 'Minsk National Airport', 'Minsk, BY')
INSERT INTO airport(aCode, aName, loc) VALUES ('KJA', 'Yemelyanovo Airport', 'Krasnoyarsk, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('OVB', 'Tolmachevo Airport', 'Novosibirsk, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('ROV', 'Platov International Airport', 'Rostov-on-Don, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('AER', 'Sochi International Airport', 'Sochi, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('SVX', 'Koltsovo Airport', 'Yekaterinburg, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('ASB', 'Ashgabat International Airport', 'Ashgabat, TM')
INSERT INTO airport(aCode, aName, loc) VALUES ('TAS', 'Tashkent International Airport', 'Tashkent, UZ')
INSERT INTO airport(aCode, aName, loc) VALUES ('ZIA', 'Zhukovsky International Airport', 'Moscow, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('DME', 'Domodedovo International Airport', 'Moscow, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('SVO', 'Sheremetyevo International Airport', 'Moscow, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('VKO', 'Vnukovo International Airport', 'Moscow, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('KZN', 'Kazan International Airport', 'Kazan, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('UFA', 'Ufa International Airport', 'Ufa, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('KUF', 'Kurumoch International Airport', 'Samara, RU')
INSERT INTO airport(aCode, aName, loc) VALUES ('BOM', 'Chhatrapati Shivaji International Airport', 'Mumbai, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('GOI', 'Dabolim Airport', 'Vasco da Gama, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('CMB', 'Bandaranaike International Colombo Airport', 'Colombo, LK')
INSERT INTO airport(aCode, aName, loc) VALUES ('HRI', 'Mattala Rajapaksa International Airport', ', LK')
INSERT INTO airport(aCode, aName, loc) VALUES ('PNH', 'Phnom Penh International Airport', 'Phnom Penh, KH')
INSERT INTO airport(aCode, aName, loc) VALUES ('REP', 'Siem Reap International Airport', 'Siem Reap, KH')
INSERT INTO airport(aCode, aName, loc) VALUES ('CCU', 'Netaji Subhash Chandra Bose International Airport', 'Kolkata, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('DAC', 'Hazrat Shahjalal International Airport', 'Dhaka, BD')
INSERT INTO airport(aCode, aName, loc) VALUES ('HKG', 'Hong Kong International Airport', 'Hong Kong, HK')
INSERT INTO airport(aCode, aName, loc) VALUES ('ATQ', 'Sri Guru Ram Dass Jee International Airport', 'Amritsar, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('DEL', 'Indira Gandhi International Airport', 'New Delhi, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('MFM', 'Macau International Airport', 'Macau, MO')
INSERT INTO airport(aCode, aName, loc) VALUES ('KTM', 'Tribhuvan International Airport', 'Kathmandu, NP')
INSERT INTO airport(aCode, aName, loc) VALUES ('BLR', 'Kempegowda International Airport', 'Bangalore, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('COK', 'Cochin International Airport', 'Kochi, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('CCJ', 'Calicut International Airport', 'Calicut, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('HYD', 'Rajiv Gandhi International Airport', 'Hyderabad, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('MAA', 'Chennai International Airport', 'Chennai, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('TRV', 'Trivandrum International Airport', 'Thiruvananthapuram, IN')
INSERT INTO airport(aCode, aName, loc) VALUES ('MLE', 'MalA(c) International Airport', 'MalA(c), MV')
INSERT INTO airport(aCode, aName, loc) VALUES ('DMK', 'Don Mueang International Airport', 'Bangkok, TH')
INSERT INTO airport(aCode, aName, loc) VALUES ('BKK', 'Suvarnabhumi Airport', 'Bangkok, TH')
INSERT INTO airport(aCode, aName, loc) VALUES ('CNX', 'Chiang Mai International Airport', 'Chiang Mai, TH')
INSERT INTO airport(aCode, aName, loc) VALUES ('HKT', 'Phuket International Airport', 'Phuket, TH')
INSERT INTO airport(aCode, aName, loc) VALUES ('DAD', 'Da Nang International Airport', 'Da Nang, VN')
INSERT INTO airport(aCode, aName, loc) VALUES ('HAN', 'Noi Bai International Airport', 'Hanoi, VN')
INSERT INTO airport(aCode, aName, loc) VALUES ('SGN', 'Tan Son Nhat International Airport', 'Ho Chi Minh City, VN')
INSERT INTO airport(aCode, aName, loc) VALUES ('MDL', 'Mandalay International Airport', 'Mandalay, MM')
INSERT INTO airport(aCode, aName, loc) VALUES ('RGN', 'Yangon International Airport', 'Yangon, MM')
INSERT INTO airport(aCode, aName, loc) VALUES ('UPG', 'Hasanuddin International Airport', 'Ujung Pandang-Celebes Island, ID')
INSERT INTO airport(aCode, aName, loc) VALUES ('DPS', 'Ngurah Rai (Bali) International Airport', 'Denpasar-Bali Island, ID')
INSERT INTO airport(aCode, aName, loc) VALUES ('DJJ', 'Sentani International Airport', 'Jayapura-Papua Island, ID')
INSERT INTO airport(aCode, aName, loc) VALUES ('SUB', 'Juanda International Airport', 'Surabaya, ID')
INSERT INTO airport(aCode, aName, loc) VALUES ('SOQ', 'Dominique Edward Osok Airport', 'Sorong-Papua Island, ID')
INSERT INTO airport(aCode, aName, loc) VALUES ('BWN', 'Brunei International Airport', 'Bandar Seri Begawan, BN')
INSERT INTO airport(aCode, aName, loc) VALUES ('CGK', 'Soekarno-Hatta International Airport', 'Jakarta, ID')
INSERT INTO airport(aCode, aName, loc) VALUES ('KNO', 'Kualanamu International Airport', ', ID')
INSERT INTO airport(aCode, aName, loc) VALUES ('KUL', 'Kuala Lumpur International Airport', 'Kuala Lumpur, MY')
INSERT INTO airport(aCode, aName, loc) VALUES ('SIN', 'Singapore Changi Airport', 'Singapore, SG')
INSERT INTO airport(aCode, aName, loc) VALUES ('BNE', 'Brisbane International Airport', 'Brisbane, AU')
INSERT INTO airport(aCode, aName, loc) VALUES ('MEL', 'Melbourne International Airport', 'Melbourne, AU')
INSERT INTO airport(aCode, aName, loc) VALUES ('YNT', 'Yantai Penglai International Airport', 'Yantai, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('ADL', 'Adelaide International Airport', 'Adelaide, AU')
INSERT INTO airport(aCode, aName, loc) VALUES ('PER', 'Perth International Airport', 'Perth, AU')
INSERT INTO airport(aCode, aName, loc) VALUES ('CBR', 'Canberra International Airport', 'Canberra, AU')
INSERT INTO airport(aCode, aName, loc) VALUES ('SYD', 'Sydney Kingsford Smith International Airport', 'Sydney, AU')
INSERT INTO airport(aCode, aName, loc) VALUES ('PEK', 'Beijing Capital International Airport', 'Beijing, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('PKX', 'Beijing Daxing International Airport', 'Beijing, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('HET', 'Baita International Airport', 'Hohhot, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('NAY', 'Beijing Nanyuan Airport', 'Beijing, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('TSN', 'Tianjin Binhai International Airport', 'Tianjin, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('TYN', 'Taiyuan Wusu Airport', 'Taiyuan, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('CAN', 'Guangzhou Baiyun International Airport', 'Guangzhou, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('CSX', 'Changsha Huanghua International Airport', 'Changsha, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('KWL', 'Guilin Liangjiang International Airport', 'Guilin City, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('NNG', 'Nanning Wuxu Airport', 'Nanning, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('SZX', 'Shenzhen Bao''an International Airport', 'Shenzhen, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('CGO', 'Zhengzhou Xinzheng International Airport', 'Zhengzhou, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('WUH', 'Wuhan Tianhe International Airport', 'Wuhan, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('HAK', 'Haikou Meilan International Airport', 'Haikou, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('SYX', 'Sanya Phoenix International Airport', 'Sanya, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('XIY', 'Xi''an Xianyang International Airport', 'Xi''an, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('UBN', 'Ulaanbaatar International Airport', 'Ulaanbaatar, MN')
INSERT INTO airport(aCode, aName, loc) VALUES ('ULN', 'Buyant-Ukhaa International Airport', 'Ulan Bator, MN')
INSERT INTO airport(aCode, aName, loc) VALUES ('KMG', 'Kunming Changshui International Airport', 'Kunming, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('XMN', 'Xiamen Gaoqi International Airport', 'Xiamen, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('FOC', 'Fuzhou Changle International Airport', 'Fuzhou, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('HGH', 'Hangzhou Xiaoshan International Airport', 'Hangzhou, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('TNA', 'Yaoqiang Airport', 'Jinan, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('NGB', 'Ningbo Lishe International Airport', 'Ningbo, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('NKG', 'Nanjing Lukou Airport', 'Nanjing, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('PVG', 'Shanghai Pudong International Airport', 'Shanghai, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('SHA', 'Shanghai Hongqiao International Airport', 'Shanghai, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('WNZ', 'Wenzhou Longwan International Airport', 'Wenzhou, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('CKG', 'Chongqing Jiangbei International Airport', 'Chongqing, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('KWE', 'Longdongbao Airport', 'Guiyang, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('CTU', 'Chengdu Shuangliu International Airport', 'Chengdu, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('URC', 'ArA 1/4mqi Diwopu International Airport', 'ArA 1/4mqi, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('HRB', 'Taiping Airport', 'Harbin, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('DLC', 'Zhoushuizi Airport', 'Dalian, CN')
INSERT INTO airport(aCode, aName, loc) VALUES ('SHE', 'Taoxian Airport', 'Shenyang, CN')
